travis:
  secure:
    BINSTAR_TOKEN: Qfl9HKYM1zfRk2MPt5ToreK8n52RqaMRyU4i3LyBhkGD8wCLxMZsSrnpW6G62mgXeLhF2XKJ3wZ/U5KtJhhNX92Ib/Q+IOYDvgQtPaZ4weuKc9Sg49HaZHxqP95iPtRazJvpnXvMx29Phk1HQ+QVCNORG5CuYUWx8o9bsgzVn3MB72BA4fV1nHc55GNK4IKBiyfYdgr02+fTUEQ4pIMIq2SRjapoThv+P2vaQdGDN8+l8q0yLY/Qgrg/gp5EGf09QX2w6WD40DMgmTfo3xNhdXA6sxFMaD36udyFtABQN4lMF5u34jWtQZP0jSa8i2t84BDs2zgi1nnrbRocqKjkwfdJticJ3LMHW4RRI5kTzG+dvmXGpUKCRFj5gsuhMSqvTD7FQllBIjXPx5TK6WGksvVKCVn4M8QnhqPJnCr4SeiqVOT6Uon0wDHso5MwWDbcpTB/Qs3j20xySUCKfHHwdkffmjBSEc2IMVFMzWsLI9LsI3fKCPVBmJlBH3OnyGATGwDS/aQrr82Ux64WQcBOTxUsVZwygIAPCFmHVv3nUDm4aRg1HmiNkkUqWzSfgToRqrpKKzo5eyq41vD2b6GIJ7/oAOWNz2UOkdWmZ30vwjcR0Htttp3BxKF9oLvK/uGVtpY8670gDJ3uSb96tWXirCPNoPpiUydeTlEFFyw9fU4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
