travis:
  secure:
    BINSTAR_TOKEN: JYjQiEuChVMNNbWqV/GB0PlRIw3AV7GtAyUK/k2oaXmciqvP60L5kiY71IKqXhcffkyrCuxD8b8RzNybt3l7z6X2s7i+R+w0Hqt9c8bPkdYnYkOzlLsjhPkoBmpzzwdLF+hRtQZNtbbwh1f6wjNZXE11eseAB1imgDC7XfVi4V/uFooTPv5zE25BA3mYrJKyloadDQ52lGUAbB8Y6XWbQU+IlbrGPF6jhsDt3taftPoLv/aXPYnNfpkcMEeCuIA90aUHk3kBUuiSjOgDoC+oZepSKSLDOGqfMw3Gc0IAHaadVWoZ3xjZyG8sNYdEjbSCc/8HmBYrlzBJFrUOx+uCJZJzJm2kZHhdjS9NIU/yoZXOL7q3CaP0MvDv/FNwneC+0lPpG3ATTo+CXizPlYZhvnp46B97GENQCi8IxrVpOc7otWzcRutmKKUbksNZ0PLGs99amyOuo7S5/0TpFUY0JDJYcc+t5cL4DBwiBXsyLvL5ZEpegFU7layIY0frmHuFOLY8DksHurcE4+7lmJC/RfH+ArJr68iGzLn79GsZ6h/MYV7lZ2vxcW4ghxywCvjIThvICO0xoczL8kijUxDifDS9mIF+vISYR2ZFInF9Ivr6pGtkPZItv1wnWVPKI6decTloqBsPbQAfE7Qn+oyxoT4CMbU+N1awkBn4/bAl0Hg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
